# ============ APPLICATION CONFIGURATION ===================

spring:
  profiles:
    active:

  datasource:
    url: ${env.DB_URL}
    username: ${env.DB_USER}
    password: ${env.DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: ${env.JWT_SECRET}

env:
  printer:
    show-values: true
    project-only: true